runtime: nodejs14
instance_class: F2
automatic_scaling:
  max_instances: 10
  min_instances: 3
inbound_services:
  - warmup
env_variables:
  REDIS_PORT: '6378'
  REDIS_PASSWORD: '70bea022-a9d1-4254-96ab-6b6b8c348d98'
