services:
  # gffft-db:
  #   image: postgis/postgis
  #   restart: always
  #   environment:
  #     POSTGRES_USER: gffft
  #     POSTGRES_PASSWORD: gffft
  #     POSTGRES_DB: gffft
  #   volumes:
  #     - gffft_db:/var/lib/postgresql/data
  #   ports:
  #     - "5442:5432"

  firebase-emulator:
    image: gffft-firebase-emulator
    platform: linux/arm64
    build:
      context: ./
      dockerfile: ./firebase-emulator/Dockerfile
    volumes:
      # - ./firebase-emulator:/app
      - ./functions:/app
      - ./firebase-emulator/data:/app/data
      - /app/node_modules
    ports:
      - "4000:4000"
      - "5000:5000"
      - "8080:8080"
      - "9099:9099"
      - "9199:9199"
    command: firebase emulators:start --project gffft-auth --import /app/data

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass 98puOInkjbO&YiubkBt8guhvjhvredrg

  api:
    image: gffft-api
    depends_on:
      - firebase-emulator
    build:
      context: ./functions
      dockerfile: ../functions/Dockerfile
    volumes:
      - ./functions:/app
      - /app/node_modules
    environment:
      SERVICE: local
      NODE_ENV: dockerCompose
      FIREBASE_AUTH_EMULATOR_HOST: "firebase-emulator:9099"
      FIRESTORE_EMULATOR_HOST: "firebase-emulator:8080"
      FIREBASE_STORAGE_EMULATOR_HOST: "firebase-emulator:9199"
      GCLOUD_PROJECT: "gffft-auth"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 98puOInkjbO&YiubkBt8guhvjhvredrg

    ports:
      - "3000:3000"

volumes:
  gffft_db: null
  cache: null
