services:
  gffft-db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: gffft
      POSTGRES_PASSWORD: gffft
      POSTGRES_DB: gffft
    volumes:
      - gffft_db:/var/lib/postgresql/data
    ports:
      - "5442:5432"
  firebase-emulator:
    image: gffft-firebase-emulator
    build: ./firebase-emulator
    volumes:
      # - ./firebase-emulator:/app
      - ./functions:/app
    ports:
      - "9099:9099"
      - "9199:9199"
      - "5000:5000"
    command: firebase emulators:start --project gffft-auth

volumes:
  gffft_db: null
