services:
  # gffft-db:
  #   image: postgis/postgis
  #   restart: always
  #   environment:
  #     POSTGRES_USER: gffft
  #     POSTGRES_PASSWORD: gffft
  #     POSTGRES_DB: gffft
  #   volumes:
  #     - gffft_db:/var/lib/postgresql/data
  #   ports:
  #     - "5442:5432"

  firebase-emulator:
    image: gffft-firebase-emulator
    build: ./firebase-emulator
    volumes:
      # - ./firebase-emulator:/app
      - ./functions:/app
      - ./firebase-emulator/data:/app/data
    ports:
      - "4000:4000"
      - "5000:5000"
      - "8080:8080"
      - "9099:9099"
      - "9199:9199"
    command: firebase emulators:start --project gffft-auth --import /app/data

  api:
    image: gffft-api
    build:
      context: ./functions
      dockerfile: ../functions/Dockerfile
    volumes:
      - ./functions:/app
    environment:
      SERVICE: local
      NODE_ENV: dockerCompose
      FIREBASE_AUTH_EMULATOR_HOST: "firebase-emulator:9099"
      FIRESTORE_EMULATOR_HOST: "firebase-emulator:8080"
      FIREBASE_STORAGE_EMULATOR_HOST: "firebase-emulator:9199"

    ports:
      - "3000:3000"

volumes:
  gffft_db: null
