services:
  api-integration-test:
    image: gffft-api
    depends_on:
      - firebase-emulator
      - redis
    build:
      context: ./functions
      dockerfile: ../functions/Dockerfile
    volumes:
      - ./functions:/app
      - /app/node_modules
    environment:
      SERVICE: local
      NODE_ENV: dockerCompose
      FIREBASE_AUTH_EMULATOR_HOST: "firebase-emulator:9099"
      FIRESTORE_EMULATOR_HOST: "firebase-emulator:8080"
      FIREBASE_STORAGE_EMULATOR_HOST: "firebase-emulator:9199"
      GCLOUD_PROJECT: "gffft-auth"
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: 98puOInkjbO&YiubkBt8guhvjhvredrg
      WAIT_HOSTS: firebase-emulator:9199,firebase-emulator:8080,redis:6379
      WAIT_TIMEOUT: 240
    command: >
      bash -c "/wait && npm install && npm run test:coverage"
