services:
  gffft-db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: gffft
      POSTGRES_PASSWORD: gffft
      POSTGRES_DB: gffft
    ports:
      - "5442:5432"
    volumes:
      - gffft_db:/var/lib/postgresql/data

volumes:
  gffft_db: